services:
    birthminder_db:
        image: mongo
        restart: always
        container_name: BirthminderDB
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_INITDB_USER_USERNAME: ${MONGO_USER_USERNAME}
            MONGO_INITDB_USER_PASSWORD: ${MONGO_USER_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        ports:
            - 27017:27017
        volumes:
            - ./data/mongo:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    birthminder_web:
        image: node:hydrogen-slim
        container_name: Birthminder
        command: /bin/sh -c "cd /srv/app && npm install && npm run dev"
        ports:
            - 3900:3000
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
        tty: true
